### ISSUE TITLE
Fix deoplete issue when launching vim

### ISSUE THREAD

**Issue by bw-matthew** [matthewfranglen/dotfiles#18]
```
[deoplete] [yarp] [deoplete] job is dead. failed establishing channel for ['python3', '/home/matthew/.vim/plugged/nvim-yarp/pythonx/yarp.py', '127.0.0.1:49226', 2, 'deoplete']
[deoplete] function <SNR>1_Main[1]..<SNR>1_LoadPlugins[22]..<SNR>1_ConfigurePlugins[3]..<SNR>1_ConfigureDeoplete[2]..deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[11]..deoplete#init#_channel[10]..yarp#core#notify[1]..yarp#core#wait_channel, line 13
Press ENTER or type command to continue
```
This happens pretty reliably when launching vim.

**Comment by matthewfranglen** [comment]
The error message does not illuminate the problem. Need more steps to reproduce.

Try updating your plugins?

**Comment by matthewfranglen** [comment]
Was able to reproduce this. This occurs when using a pyenv. Installing neovim into the pyenv with

```bash
pip install neovim
```

Fixed this issue. I'm not sure how to resolve this well - I usually want vim to launch in the virtualenv because I put the linter there, and it's set using `pyenv local`.

**Comment by matthewfranglen** [comment]
Installing neovim currently results in:

```
greenlet==0.4.12
msgpack-python==0.5.1
neovim==0.2.0
```
