### ISSUE TITLE
Make it easier for gitflow and hub to interact

### ISSUE THREAD

**Issue by bw-matthew** [matthewfranglen/dotfiles#37]
gitflow needs to identify the fork as the remote to operate over.
This is achieved with the `gitflow.origin` option:

```
git config gitflow.origin matthewfranglen
```

hub needs the git checkout to know about the default branch of the remote, which usually starts as master and becomes develop after some time:

```
git remote set-head origin develop
```

A way to correctly set up a repo for gitflow and hub development is desirable.

**Comment by matthewfranglen** [comment]
The gitflow.origin value can be derived based on the user saved in `~/.config/hub`.
